### ISSUE TITLE
Unable to show dialog

### ISSUE THREAD

**Issue by zaffer125** [waynegm/imgNotes#27]
Hi,

First of all thank you for such a great library.

My requirement is to show the NoteDialog immediately after plotting the notes, as the user need not click the note marker to see the details.

My issues is I am unable to show the NoteDialog on launch, after adding the notes to the image.

Please help, stuck with this since yesterday.

Regards,

**Comment by waynegm** [comment]
So you want to show dialogs for all the markers at once or just the dialog for the first marker?

**Comment by zaffer125** [comment]
I would like to show the dialogs for all the markers at once. 

    On Wednesday, 16 November 2016, 16:49, Wayne Mogg <notifications@github.com> wrote:
 

 So you want to show dialogs for all the markers at once or just the dialog for the first marker? —

**Comment by waynegm** [comment]
What is supposed to happen when the user zooms and pans - do you expect the dialogs to move with the marker?

**Comment by zaffer125** [comment]
Yes, the dialog should move with the marker. 

    On Thursday, 17 November 2016, 13:33, Wayne Mogg <notifications@github.com> wrote:
 

 What is supposed to happen when the user zooms and pans - do you expect the dialogs to move with the marker?—

**Comment by waynegm** [comment]
You should be able to do this with a custom "onAdd" callback. Have a look at the "custom_marker.html" file in the examples folder. That creates a div as the marker and puts a letter into it. Replace the letter with the note text and add some css to get the appearance you want and your done. There are plenty of tutorials online which show how to use css to create nice looking callouts. 

Also define an empty onShow callback since you don't want to be popping up a dialog box if th euser clicks on the note.
