### ISSUE TITLE
Show notes as markers appear

### ISSUE THREAD

**Issue by geekysneaks** [waynegm/imgNotes#31]
Hi,

I would like to show the notes at the same time the markers appears. I looked at closed issue (#27 and it didn't make sense). 

Can you please help?

**Comment by geekysneaks** [comment]
Anyone?

**Comment by waynegm** [comment]
I've just pushed a new example to the GitHub master called "examples/always_visible_notes.html" which shows how to display the notes from the start. Because the notes must move around with the markers I've added a placeholder for the note text as the marker. The only trick is the note text is not available in the "onAdd" callback and it has to be set in a custom "onUpdateMarker" callback. You may have plans for something more elaborate but hope this gets you started.
