### ISSUE TITLE
ImgNotes Plugin for IOS Development

### ISSUE THREAD

**Issue by virajshah25** [waynegm/imgNotes#43]
do you know any plugin which works for ios?

**Comment by waynegm** [comment]
I didn't know this didn't work on IOS as I don't have any IOS devices to test on so that is a bit disappointing. You could have a look at my [imgViewer2](https://github.com/waynegm/imgViewer2) plugin which uses the [Leaflet](http://leafletjs.com/index.html) mapping widget for the underlying display which I believe has good support on IOS. Examples [6](https://waynegm.github.io/imgViewer2/basic_note.html) and [7](https://waynegm.github.io/imgViewer2/basic_note_with_plugins.html) show how to simply extend imgViewer2 to display markers and notes.
